/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export interface EditEntry {
  'title' : string,
  'entryType' : EntryType,
  'body' : string,
  'tags' : Array<string>,
}
export interface Entry {
  'id' : EntryId,
  'status' : PublishedStatus,
  'title' : string,
  'entryType' : EntryType,
  'body' : string,
  'createdAt' : Timestamp,
  'tags' : Array<string>,
  'publishedAt' : [] | [Timestamp],
  'author' : UserId,
  'updatedAt' : Timestamp,
}
export interface EntryFilter {
  'search' : [] | [string],
  'statusFilter' : [] | [PublishedStatus],
  'typeFilter' : [] | [EntryType],
}
export type EntryId = bigint;
export type EntryType = { 'blog' : null } |
  { 'note' : null } |
  { 'diary' : null };
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface NewEntry {
  'title' : string,
  'entryType' : EntryType,
  'body' : string,
  'tags' : Array<string>,
}
export type PublishedStatus = { 'published' : null } |
  { 'draft' : null };
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type SortOrder = { 'newestFirst' : null } |
  { 'oldestFirst' : null };
export interface StyleReview {
  'suggestions' : Array<StyleSuggestion>,
  'wordCount' : bigint,
  'readingTimeMinutes' : bigint,
}
export type StyleRule = { 'longSentence' : null } |
  { 'readability' : null } |
  { 'passiveVoice' : null } |
  { 'repeatedWords' : null };
export interface StyleSuggestion {
  'rule' : StyleRule,
  'flaggedText' : string,
  'suggestion' : string,
  'endIndex' : bigint,
  'startIndex' : bigint,
}
export type Timestamp = bigint;
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createEntry' : ActorMethod<[NewEntry], Entry>,
  'deleteEntry' : ActorMethod<[EntryId], undefined>,
  'editEntry' : ActorMethod<[EntryId, EditEntry], Entry>,
  'execute' : ActorMethod<[string], Result>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getEntry' : ActorMethod<[EntryId], [] | [Entry]>,
  'getPublicEntry' : ActorMethod<[EntryId], [] | [Entry]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listMyEntries' : ActorMethod<[EntryFilter], Array<Entry>>,
  'listPublicFeed' : ActorMethod<
    [[] | [string], [] | [string], SortOrder],
    Array<Entry>
  >,
  'publishEntry' : ActorMethod<[EntryId], Entry>,
  'reviewEntryStyle' : ActorMethod<[string], StyleReview>,
  'schema' : ActorMethod<[], string>,
  'unpublishEntry' : ActorMethod<[EntryId], Entry>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];