/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EntryType = IDL.Variant({
  'blog' : IDL.Null,
  'note' : IDL.Null,
  'diary' : IDL.Null,
});
export const NewEntry = IDL.Record({
  'title' : IDL.Text,
  'entryType' : EntryType,
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const EntryId = IDL.Nat;
export const PublishedStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const UserId = IDL.Principal;
export const Entry = IDL.Record({
  'id' : EntryId,
  'status' : PublishedStatus,
  'title' : IDL.Text,
  'entryType' : EntryType,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Opt(Timestamp),
  'author' : UserId,
  'updatedAt' : Timestamp,
});
export const EditEntry = IDL.Record({
  'title' : IDL.Text,
  'entryType' : EntryType,
  'body' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const EntryFilter = IDL.Record({
  'search' : IDL.Opt(IDL.Text),
  'statusFilter' : IDL.Opt(PublishedStatus),
  'typeFilter' : IDL.Opt(EntryType),
});
export const SortOrder = IDL.Variant({
  'newestFirst' : IDL.Null,
  'oldestFirst' : IDL.Null,
});
export const StyleRule = IDL.Variant({
  'longSentence' : IDL.Null,
  'readability' : IDL.Null,
  'passiveVoice' : IDL.Null,
  'repeatedWords' : IDL.Null,
});
export const StyleSuggestion = IDL.Record({
  'rule' : StyleRule,
  'flaggedText' : IDL.Text,
  'suggestion' : IDL.Text,
  'endIndex' : IDL.Nat,
  'startIndex' : IDL.Nat,
});
export const StyleReview = IDL.Record({
  'suggestions' : IDL.Vec(StyleSuggestion),
  'wordCount' : IDL.Nat,
  'readingTimeMinutes' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createEntry' : IDL.Func([NewEntry], [Entry], []),
  'deleteEntry' : IDL.Func([EntryId], [], []),
  'editEntry' : IDL.Func([EntryId, EditEntry], [Entry], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEntry' : IDL.Func([EntryId], [IDL.Opt(Entry)], []),
  'getPublicEntry' : IDL.Func([EntryId], [IDL.Opt(Entry)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listMyEntries' : IDL.Func([EntryFilter], [IDL.Vec(Entry)], []),
  'listPublicFeed' : IDL.Func(
      [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), SortOrder],
      [IDL.Vec(Entry)],
      ['query'],
    ),
  'publishEntry' : IDL.Func([EntryId], [Entry], []),
  'reviewEntryStyle' : IDL.Func([IDL.Text], [StyleReview], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'unpublishEntry' : IDL.Func([EntryId], [Entry], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EntryType = IDL.Variant({
    'blog' : IDL.Null,
    'note' : IDL.Null,
    'diary' : IDL.Null,
  });
  const NewEntry = IDL.Record({
    'title' : IDL.Text,
    'entryType' : EntryType,
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const EntryId = IDL.Nat;
  const PublishedStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const UserId = IDL.Principal;
  const Entry = IDL.Record({
    'id' : EntryId,
    'status' : PublishedStatus,
    'title' : IDL.Text,
    'entryType' : EntryType,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Opt(Timestamp),
    'author' : UserId,
    'updatedAt' : Timestamp,
  });
  const EditEntry = IDL.Record({
    'title' : IDL.Text,
    'entryType' : EntryType,
    'body' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const EntryFilter = IDL.Record({
    'search' : IDL.Opt(IDL.Text),
    'statusFilter' : IDL.Opt(PublishedStatus),
    'typeFilter' : IDL.Opt(EntryType),
  });
  const SortOrder = IDL.Variant({
    'newestFirst' : IDL.Null,
    'oldestFirst' : IDL.Null,
  });
  const StyleRule = IDL.Variant({
    'longSentence' : IDL.Null,
    'readability' : IDL.Null,
    'passiveVoice' : IDL.Null,
    'repeatedWords' : IDL.Null,
  });
  const StyleSuggestion = IDL.Record({
    'rule' : StyleRule,
    'flaggedText' : IDL.Text,
    'suggestion' : IDL.Text,
    'endIndex' : IDL.Nat,
    'startIndex' : IDL.Nat,
  });
  const StyleReview = IDL.Record({
    'suggestions' : IDL.Vec(StyleSuggestion),
    'wordCount' : IDL.Nat,
    'readingTimeMinutes' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createEntry' : IDL.Func([NewEntry], [Entry], []),
    'deleteEntry' : IDL.Func([EntryId], [], []),
    'editEntry' : IDL.Func([EntryId, EditEntry], [Entry], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEntry' : IDL.Func([EntryId], [IDL.Opt(Entry)], []),
    'getPublicEntry' : IDL.Func([EntryId], [IDL.Opt(Entry)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listMyEntries' : IDL.Func([EntryFilter], [IDL.Vec(Entry)], []),
    'listPublicFeed' : IDL.Func(
        [IDL.Opt(IDL.Text), IDL.Opt(IDL.Text), SortOrder],
        [IDL.Vec(Entry)],
        ['query'],
      ),
    'publishEntry' : IDL.Func([EntryId], [Entry], []),
    'reviewEntryStyle' : IDL.Func([IDL.Text], [StyleReview], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'unpublishEntry' : IDL.Func([EntryId], [Entry], []),
  });
};

export const init = ({ IDL }) => { return []; };